{"172ad483235f367a3c49c4be637a35a5":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"d6baabb3860c10de","status":"passed","time":{"start":1750760054442,"stop":1750760058235,"duration":3793}}]},"9b838270607c70a0dc6d4bc052724e9d":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"8b26e9e0fcd06190","status":"passed","time":{"start":1750760058320,"stop":1750760060707,"duration":2387}}]},"804cedfc076fc78841243ccaeb24eb4e":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"b877b9f8e61ac847","status":"passed","time":{"start":1750760045176,"stop":1750760053307,"duration":8131}}]},"e5f0739cfe30b11d9af2e3eb3e76cb78":{"statistic":{"failed":1,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"65cc41b068c28c00","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Cannot read properties of undefined (reading 'response')\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1750760066810,"stop":1750760074533,"duration":7723}}]},"6a99d9bd1ed9e89c0c62930a1276ee53":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"ffffc2c0a5e7c20d","status":"passed","time":{"start":1750760060798,"stop":1750760062869,"duration":2071}}]}}